spring.application.name=cabinet

# ========== POSTGRESQL ==========
spring.datasource.url=jdbc:postgresql://localhost:5432/casafami
spring.datasource.username=postgres
spring.datasource.password=415011
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== JPA / HIBERNATE ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========== SERVEUR ==========
server.port=8080

# ========== JWT ==========
jwt.secret=NDA0RTYzNTM2RTcxMzI3QTY5NkI1OTdCM0Y0NDIyMjY0ODU2NkI1OTdCM0Y0NDIyNjQ=
jwt.expiration=86400000

# ========== SMS ==========
sms.mode=simulation